Crud
Semc4ik1/CarsJDBC pull request #1
Opened 2024-08-02 18:07 UTC by Semc4ik1

2024-08-02 20:39 UTC, eashutov requested changes

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsUpdate.java
> +            scanner.nextLine();
Очень прикольное считывание в никуда

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsUpdate.java
> +        scanner.nextLine();
Еще одно очень прикольное считывание в никуда

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsUpdate.java
> +            switch (choice) {
Вообще лучше уж всё сразу спрашивать и менять сущность целиком (а если указано старое значение или ничего, то не менять), тогда не будет этого свитча убогого.

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    public List<Car> selectAll() {
Странно, что для всех типов запросов, кроме selectAll у тебя есть отдельный класс

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +    public CarsCreator(CarDatabaseProvider databaseProvider) {
Неясно зачем в конструктор передавать этот объект, если с ним всё равно ничего не делается

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +public class CarsCreator implements CarsAdder {
Вообще не вижу смысла ни в классе, ни в интерфейсе, который он реализует

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +            if (i == 2) {
Такие if в цикле, которые прогоняются постоянно, но при этом подразумевается, что они на весь цикл должны сработать только один раз - это плохое решение

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +        for (int i = 0; i < questions.length; i++) {
Лучше бы оставил как было)
Вроде как расчет на какую-то "гибкость", типа сколько вопросов - столько и инпутов, да только всё равно потом сеттеры вызываются внизу отдельно.

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/SqlQueries.java
> +    SELECT_ALL_CARS("SELECT * FROM cars;");
А че остальные не добавил?

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/deleteCar/CarsDelete.java
> +             PreparedStatement statement = connection.prepareStatement("DELETE FROM cars WHERE id = ?")) {
Запрос можно было вынести либо в константу, либо в enum

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/deleteCar/CarsDelete.java
> +    public CarsDelete(CarDatabaseProvider databaseProvider) {
Опять же непонятно зачем переданный в конструктор параметр, который потом ничему не присваивается

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/deleteCar/CarsDelete.java
> +public class CarsDelete implements CarsRemove {
Так же не особо вдупляю на кой было делать отдельный класс с интерфейсом

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    public static Connection getConnection() throws SQLException {
Не думаю, что давать Connection кому угодно и где угодно - это хорошая идея. А в текущий момент именно так и есть.
Мы можем в любом участке кода сделать `Connection connection = CarDatabaseProvider.getConnection();` и насрать в базу данных что угодно, без ограничений.
А если бы только данный класс мог работать с БД, его полями и коннектами, то в целом ничего не произошло бы, кроме тех методов, который и дает этот класс.

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsUpdate.java
> +                    updateQuery = "UPDATE cars SET name = ?";
Ты во всех своих запросах делаешь обновление абсолютно всех записей. Несмотря на то, что ты спросил в самом начале этого метода id машины, которую надо изменить, ты не сделал нигде `Where id = ?`.

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    private static final String PASSWORD = "twerk228";
Можно попробовать эти константы вынести в properties. Чтобы они задавались из некоторого файла конфигурации в resources.

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/Main.java
> +    public static void main(String[] args) {
Тут везде сплошной хардкод. Последовательность действий задана слишком четко. Ты должен у пользователя спросить, что ему надо сделать: прочитать все записи, обновить, удалить, прочитать конкретную запись по id.

2024-08-02 20:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +                     "INSERT INTO cars ( model, color, year, manufacturer, license_plate) VALUES ( ?, ?, ?, ?, ?)")) {
Запрос можно в константу или в enum вынести

2024-08-03 08:19 UTC, Semc4ik1 commented on src/main/java/ru/gumenuk/addCar/CarsUpdate.java
> +            switch (choice) {
Я думал над этим, я не понимаю как это можно реализовать, если есть идейка, то интересно послушать

2024-08-03 08:20 UTC, Semc4ik1 commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +    public CarsCreator(CarDatabaseProvider databaseProvider) {
Если не передам этот обьект в конструктор, в мейне передаваемый параметр перестанет работать

2024-08-03 08:21 UTC, Semc4ik1 commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    public static Connection getConnection() throws SQLException {
Только есть идея перенести все эти методы по созданию и удалению в основной класс где идет подключение, как обсуждали до этого, только так

2024-08-03 12:38 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsUpdate.java
> +            switch (choice) {
Ну ты как создаешь, так и это делай. Можно даже тот же метод наверное вызывать. Только желательно указывать старое значение, если есть.

2024-08-03 12:39 UTC, eashutov commented on src/main/java/ru/gumenuk/addCar/CarsCreator.java
> +    public CarsCreator(CarDatabaseProvider databaseProvider) {
Ну может потому что ты объект передаешь в пустой конструктор?)))

2024-08-03 12:41 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    public static Connection getConnection() throws SQLException {
Ну пусть так и будет, либо можешь сделать абстрактный класс, в котором будут константы и метод getConnection уже реализованный.
Можно даже типизировать его дженериком, чтобы наследники производили работу с определенным типом сущности.

2024-08-03 13:52 UTC, eashutov requested changes

2024-08-03 13:52 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    public static Connection getConnection() throws SQLException {
Этот метод либо protected, либо private. Чтоб никто не мог его вызвать.

2024-08-03 13:52 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +    private Car collectCarDetails() {
Этот метод не должен быть тут. Ты дополнительную ответственность накидываешь на класс, который должен только с БД работать. У тебя он еще и у пользователя спрашивает инфу.
По хорошему `addCar()` должен принимать car, т.е. `addCar(Car car);`.
А этот метод убрать.
Соответственно где-то снаружи у нас должна коллектиться машина.

2024-08-03 13:52 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/Main.java
> +                case 1:
Используй стрелочку вместо : и break. Если где-то случайно break забудешь, то может произойти что-то очень страшное. А со стрелочкой не забудешь. Возможно Intellij Idea даже предложит сама это поменять.

2024-08-03 13:52 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/Main.java
> +            System.out.print("Ваш выбор: ");
Вместо кучи System.out.println() можно использовать один, а внутри через `\n` строчки писать.
Либо еще проще есть механизм с тремя кавычками.
```
System.out.println("""
1 - Добавить автомобиль
2 - Изменить автомобиль
3 - Удалить автомобиль
и т.д.
""");
```

2024-08-03 13:52 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +            String checkQuery = "SELECT * FROM cars WHERE id = ?";
Это можно в enum вынести.
И вообще для выбора по id должен быть отдельный метод.

2024-08-06 14:55 UTC, eashutov requested changes

2024-08-06 14:55 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/Main.java
> +                        scanner.close();
при try-with-resources необязательно прописывать close()

2024-08-06 14:55 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +                car.setLicensePlate(resultSet.getString(6));
Не забывай форматирование Ctrl Alt L

2024-08-06 14:55 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +            System.out.println("Отлично, машина с id номер " + affected + " обновлено");
Насколько я знаю, executeUpdate() возвращает количество обновленных строк.
Ты пишешь, что машина с айди [количество обновленных строк] обновлена. Почему тут affected, а не id?

2024-08-06 14:55 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +             PreparedStatement statement = connection.prepareStatement("SELECT * FROM cars WHERE id = ?;")) {
Здесь надо константный запрос из enum, а не просто стрингой.

2024-08-06 14:55 UTC, eashutov commented on src/main/java/ru/gumenuk/connection/CarDatabaseProvider.java
> +                throw new IllegalArgumentException("Cannot find car with id = " + id);
Ты оставил тут рантайм, хотя я говорил, что программа не должна бы падать из-за неверного id. Должна быть обработка исключения, типа неправильный айди, введите другой.
Тут можно было бы сделать кастомный эксепшн CarNotFoundException extends Exception к примеру и ловить его в основном main цикле while как-то.

2024-08-07 09:53 UTC, merged